"""initial_agent_schema

Revision ID: 9e1095778d39
Revises: 
"""
import sqlalchemy as sa
from alembic import op

revision = '9e1095778d39'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_key_hash', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_assets_owner_key_hash'), 'assets', ['owner_key_hash'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('owner_key_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('asset_ids', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('critic_score', sa.Float(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('workflow_data', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_owner_key_hash'), 'generations', ['owner_key_hash'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('owner_key_hash', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('owner_key_hash', 'key')
    )
    op.create_index(op.f('ix_idempotency_records_generation_id'), 'idempotency_records', ['generation_id'], unique=False)
    op.create_table('generation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_events_generation_id'), 'generation_events', ['generation_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_events_generation_id'), table_name='generation_events')
    op.drop_table('generation_events')
    op.drop_index(op.f('ix_idempotency_records_generation_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_generations_owner_key_hash'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_assets_owner_key_hash'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
